# Generated by Django 5.0.1 on 2024-11-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innofunds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fintechfriend',
            name='type',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fintechfriend',
            name='user1_pk',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fintechfriend',
            name='user2_pk',
            field=models.PositiveIntegerField(),
        ),
    ]
