# Generated by Django 5.0.1 on 2024-11-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innofunds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fintechuser',
            name='username',
            field=models.CharField(max_length=255, verbose_name='username'),
        ),
    ]
