# Generated by Django 5.0.1 on 2024-02-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_fintechuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='fintechuser',
            name='first_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='fintechuser',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
